### ISSUE TITLE
Unable to run chapter01/initial-example-app

### ISSUE THREAD

**Issue by sfali** [PacktPublishing/Mastering-Akka#4]
Hi There,

I am unable to run chapter01/initial-example-app, following expections start coming once bookstore initialized in docker:
```text
16:14:19,614 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
16:14:19,614 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
16:14:19,614 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/opt/docker/lib/com.packt.masteringakka.initial-example-server-0.1.0.jar!/logback.xml]
16:14:19,636 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@33d512c1 - URL [jar:file:/opt/docker/lib/com.packt.masteringakka.initial-example-server-0.1.0.jar!/logback.xml] is not of type file
16:14:19,738 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
16:14:19,741 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
16:14:19,826 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
16:14:19,829 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
16:14:19,829 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
16:14:19,832 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
16:14:19,844 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
16:14:19,864 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
16:14:19,868 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@71e9ddb4 - Registering current configuration as safe fallback point
2017-12-28 16:14:20 [main] WARN  com.zaxxer.hikari.HikariConfig - The jdbcConnectionTest property is now deprecated, see the documentation for connectionTestQuery
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - HikariCP pool psqldb configuration:
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionCustomizer............com.zaxxer.hikari.AbstractHikariConfig$1@2ddc9a9f
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionCustomizerClassName...
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery.............select 1
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............1000
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=<masked>}
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - driverClassName.................org.postgresql.Driver
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailFast..........false
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbc4ConnectionTest.............false
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................jdbc:postgresql://postgres:5432/akkaexampleapp
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........0
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................50
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................10
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - password........................<masked>
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - poolName........................psqldb
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................false
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - username........................docker
2017-12-28 16:14:20 [main] DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............1000
2017-12-28 16:14:20 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariCP pool psqldb is starting.
2017-12-28 16:14:21 [HikariCP connection filler (pool psqldb)] DEBUG com.zaxxer.hikari.pool.PoolUtilities - psqldb - Connection.setNetworkTimeout() not supported
2017-12-28 16:14:21 [HikariCP connection filler (pool psqldb)] DEBUG com.zaxxer.hikari.pool.PoolUtilities - Closing connection org.postgresql.jdbc4.Jdbc4Connection@3fa71640
2017-12-28 16:14:21 [HikariCP connection filler (pool psqldb)] DEBUG com.zaxxer.hikari.pool.HikariPool - Connection attempt to database psqldb failed: This ResultSet is closed.
org.postgresql.util.PSQLException: This ResultSet is closed.
at org.postgresql.jdbc2.AbstractJdbc2ResultSet.checkClosed(AbstractJdbc2ResultSet.java:2674) ~[postgresql.postgresql-9.1-901.jdbc4.jar:na]
at org.postgresql.jdbc2.AbstractJdbc2ResultSet.setFetchSize(AbstractJdbc2ResultSet.java:1791) ~[postgresql.postgresql-9.1-901.jdbc4.jar:na]
at org.postgresql.jdbc4.Jdbc4Statement.createResultSet(Jdbc4Statement.java:39) ~[postgresql.postgresql-9.1-901.jdbc4.jar:na]
at org.postgresql.jdbc2.AbstractJdbc2Statement$StatementResultHandler.handleResultRows(AbstractJdbc2Statement.java:211) ~[postgresql.postgresql-9.1-901.jdbc4.jar:na]
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1772) ~[postgresql.postgresql-9.1-901.jdbc4.jar:na]
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257) ~[postgresql.postgresql-9.1-901.jdbc4.jar:na]
at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500) ~[postgresql.postgresql-9.1-901.jdbc4.jar:na]
at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374) ~[postgresql.postgresql-9.1-901.jdbc4.jar:na]
at org.postgresql.jdbc2.AbstractJdbc2Connection.execSQLUpdate(AbstractJdbc2Connection.java:263) ~[postgresql.postgresql-9.1-901.jdbc4.jar:na]
at org.postgresql.jdbc2.AbstractJdbc2Connection.getTransactionIsolation(AbstractJdbc2Connection.java:775) ~[postgresql.postgresql-9.1-901.jdbc4.jar:na]
at com.zaxxer.hikari.pool.BaseHikariPool.addConnection(BaseHikariPool.java:446) ~[com.zaxxer.HikariCP-java6-2.3.7.jar:na]
at com.zaxxer.hikari.pool.BaseHikariPool$1.run(BaseHikariPool.java:413) [com.zaxxer.HikariCP-java6-2.3.7.jar:na]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
```
I tried adding _depends_on_ in docker-compose.yml file to have _bookstore_ to be depended on _postgres_, but no avail.

By the way I am using windows 7.

Regards,

Syed

**Comment by sfali** [comment]
Upgrading `slick` and `postgres` libraries resolved this issue

**Comment by mprzydatek** [comment]
@sfali it works - thanks a lot!

**Comment by shamoh** [comment]
See my pull request https://github.com/PacktPublishing/Mastering-Akka/pull/8 that fixes the issue.

**Comment by shamoh** [comment]
@dominicpereira92 The PR has been merged. I think you can close the issue.

**Comment by kinowarrior** [comment]
Thanks for this fix. Unfortunately, the zip download on the Packt website is stale & didn't contain the updated merge. Appreciated.
